version: '3.4'

services:
  complainmanagement.api:
    image: ${DOCKER_REGISTRY-}complainmanagementapi
    build:
      context: .
      dockerfile: ComplainManagement.API/Dockerfile

  complaindb:
    image: mcr.microsoft.com/mssql/server:2017-latest
